name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
    
    - name: Lint
      run: golangci-lint run ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        fail_ci_if_error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Build
      run: go build -v ./...
    
    - name: Create release artifact
      run: |
        GOOS=linux GOARCH=amd64 go build -o logstream-linux-amd64 ./cmd/logstream
        GOOS=darwin GOARCH=amd64 go build -o logstream-darwin-amd64 ./cmd/logstream
        GOOS=windows GOARCH=amd64 go build -o logstream-windows-amd64.exe ./cmd/logstream
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          logstream-linux-amd64
          logstream-darwin-amd64
          logstream-windows-amd64.exe

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: binaries
    
    - name: Make executable
      run: chmod +x logstream-linux-amd64
    
    - name: Create test logs
      run: |
        mkdir -p test_logs
        echo "2023-05-01 12:00:00 INFO test: Test log 1" > test_logs/test1.log
        echo "2023-05-01 12:01:00 ERROR test: Test log 2" >> test_logs/test1.log
    
    - name: Start LogStream API server
      run: |
        ./logstream-linux-amd64 serve --storage disk --storage-path ./logs &
        sleep 2  # Wait for server to start
    
    - name: Collect logs
      run: |
        ./logstream-linux-amd64 collect --sources file://$(pwd)/test_logs/test1.log --storage disk --storage-path ./logs
        sleep 2  # Wait for processing
    
    - name: Query logs
      run: |
        ./logstream-linux-amd64 query --filter "Test" --storage disk --storage-path ./logs > query_results.json
    
    - name: Verify query results
      run: |
        if ! grep -q "Test log" query_results.json; then
          echo "Query results do not contain expected log entries"
          cat query_results.json
          exit 1
        fi

  deploy-terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    
    - name: Terraform Format
      run: terraform fmt -check -recursive
      working-directory: ./terraform
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform
